core/urls.py
from cmath import pi
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

app_name ='core'

urlpatterns = [
    path("",views.LoginPage, name='loginpage'),
    path('dashboard/', views.DashBoard, name='dashboard'),
    path('dashboard/add', views.AddImage, name='addimage'),
    path('dashboard/edit/<int:pk>', views.EditImage, name='editimage'),
    path('dashboard/delete/<int:pk>', views.DeleteImage, name='deleteimage'),
    
    path("accounts/login/",views.LoginPage, name='loginpage'),
    path('logout/', views.LogoutPage, name='logoutpage'),
    
    
    
]


# Only for Development propouse
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hatico/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
   
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

core/models.py
import os
import re
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

def user_directory_path(instance, filename):
    #esta opción elimina todos los caracteres especiales
    #espacios en blanco tambien
    filename = re.sub ( '[^A-Za-z0-9_.]+', '', filename )
     # used to save avatar of user
    return 'user_{0}/{1}'.format ( str ( instance.user.username ) + '/images', filename )


# fk	field	models.ForeignKey()
# m2m	field	models.ManyToManyField()
# o2o	field	models.OneToOneField()

class ImageCategory(models.Model):
    description = models.CharField(max_length=120, blank=False)
    created_at = models.DateTimeField ( auto_now_add=True)

    def __str__(self):
        return self.description


class ImageBank(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    categories = models.ManyToManyField(ImageCategory)
    title = models.CharField(max_length=20, blank=False)
    description = models.TextField(max_length=120,  blank=True, default="Coloque aquí una breve descripción de la imagen")
    image = models.ImageField(
         upload_to = user_directory_path, 
         blank=False,
         default=None,
         verbose_name="Imagen"
     )
    created_at = models.DateTimeField ( auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{str(self.user)} | {self.title}'

    # return all categories asociated to the images.
    @property
    def data_category(self):
        qs = self.categories.all()
        value=""
        for x in qs:
            value += f'{x.pk},' 
        return value[:-1]
    
    @property
    def file_ext(self):
        # unpacking the tuple
        f_name, f_ext = os.path.splitext(str(self.image))
        return f_ext

    # Method used to delete the file into the disk
    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args,**kwargs)













    

core/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.forms import ModelForm
from core.models import *

class ImageForm(ModelForm):
    title = forms.CharField(
    label='*Título.',
    required=True,
    max_length=20,
    widget=forms.TextInput(attrs={'class': 'form-control', }))

    description = forms.CharField(
    label='*Descripción.',
    required=True,
    widget=forms.Textarea(attrs={'class': 'form-control',
                                    'cols': 30,
                                    'rows': 4,
                                    'maxlength': '120',
                                    }))
   
    categories = forms.MultipleChoiceField(
        label='*Categorías actuales.',
        required=True,
        widget=forms.CheckboxSelectMultiple(
        attrs={'class':'category-check'}
        ),
        choices=[
            (c.pk, c.description) for c in ImageCategory.objects.all().order_by('description')],
           
    )

    image = forms.FileField (
    label='*Imagen.',
    help_text="Formatos aceptados:   .bmp,   .gif,   .jpeg   .jpg,   .png   .tiff,   .mpeg,   .pdf", 
    required=True,
    validators=[FileExtensionValidator([
        'bmp',
        'gif',
        'jpeg',
        'jpg',
        'png',
        'tiff',
        'mpeg',
        'pdf'
    ])],
    widget=forms.FileInput(
        {'class':'custom-file-input'}
        
    )
    )

    class Meta:
        model = ImageBank
        fields = [
            'title',
            'description',
            'categories',
            'image',

        ]

core/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from core.decorators import unauthenticated_user
from core.forms import ImageForm
from core.models import *
from core.functions import *


# Create your views here.

@unauthenticated_user
def LoginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:dashboard')
        else:
            # return ilvalid login page
            messages.error(request,'Tu dirección electrónica/contraseña no son válidas, o tu cuenta está desactivada.')
    
    return render(request, 'core/login.html')


def LogoutPage(request):
    logout(request)
    return redirect('core:loginpage')

@login_required
def DashBoard(request):
    images = request.user.imagebank_set.select_related('user')
    categories = ImageCategory.objects.all().order_by('description')

    if not images:
        msg='No tienes imágenes cargadas.'
    else:
        msg=''


    context={
        'images':images,
        'categories':categories,
        'msg':msg,

    }

    return render(request, 'core/dashboard.html', context)

@login_required
def AddImage(request):
    form = ImageForm()
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
           
            image = form.save(commit=False)
            image.user = request.user
            # I sav before in order to get the img.pk
            image.save()
            
            # to save a respective categories into the m2m relation
            # I build the getImateCategories function, taht return a list
            # and I used the * to  expand that list into arguments :)
            image.categories.add(*getImageCategories(request.POST))
          
            messages.success(
                request, ":) ¡La imagen se ha guardado correctamente!")
        else:
            messages.error(request, ":( Algo ha salido mal, posiblemente estés intentando subir un tipo de fichero no válido. ¡Intenta de nuevo!")
        return redirect('core:dashboard')
    context = {
        'form': form,
        'add' : True,
    }
    
    return render(request, 'core/crud_image.html', context)

@login_required
def EditImage(request, pk):
    image = ImageBank.objects.get(pk=pk)
    img_selected = image.categories.all().order_by('description')
    img_to_select = ImageCategory.objects.exclude(id__in = img_selected) 
   
      
    form = ImageForm(instance=image)

    if request.method == "POST" :
        form = ImageForm(request.POST, request.FILES, instance=image)
      
        if form.is_valid():
            form.save()
            if request.FILES:
                messages.success(
                request, ":) El registro se ha actualizado con el nuevo fichero.")

            messages.success(
                request, ":) ¡La imagen se ha guardado correctamente!")
        
            return redirect('core:dashboard')

    context = {
        'form'              :form,
        'image'             :image,
        'edit'              :True,
        'img_to_select'     :img_to_select,
        'img_selected'      :img_selected,
        
    }
    return render(request, 'core/crud_image.html', context)

@login_required
def DeleteImage(request, pk):
    image = ImageBank.objects.get(pk=pk)
    img_selected = image.categories.all().order_by('description')
    
    form = ImageForm(instance=image)
    
    if request.method == "POST" :
        image.delete()
        messages.success(
                request, ":) ¡La imagen se ha eliminado correctamente!")
        
        
        return redirect('core:dashboard')

    context = {
        'form'              :form,
        'image'             :image,
        'delete'            :True,
        'img_selected'      :img_selected,
        
    }
    return render(request, 'core/crud_image.html', context)
   

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{{apptitle}}{% endblock %}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}" />

    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />

    {% block styles %} {% endblock styles %}

    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/dist/css/adminlte.min.css' %}" />

    <!-- LOCAL CSS -->
    <link href="{% static 'core/custom/css/styles.css' %}" rel="stylesheet" />

</head>

{% block content %}



<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.2.0/dist/js/adminlte.min.js' %}"></script>


{% block scripts %}
{% endblock scripts %}



{% endblock content %}

</html>

core/templates/core/crud_image.html
{% extends "core/layout.html" %}
{% load static %}
{% block title %} {% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />
<!-- SweetAlert2 -->
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
<!-- Toastr -->
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/toastr/toastr.min.css' %}">
{% endblock styles %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h4 class="card-title">Gestión de Imágen...!</h4>
            </div>
            {% include 'core/iferror.html' %}
            <form id="myCrudForm" action="" method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="card-body">

                    <div class="form-row">
                        <div class="col">
                            <div class="form-group">
                                <span class="text-warning">
                                    {{form.title.label}}
                                </span>
                                {% if not delete %}
                                {{form.title}}
                                {% else %}
                                <div class="bg-gray disable color-palette border p-3 rounded">
                                    {{image.title}}
                                </div>
                                {% endif %}


                                <br>
                                <span class="text-warning">
                                    {{form.description.label}}
                                </span>
                                {% if not delete %}
                                {{form.description}}
                                {% else %}
                                <div class="bg-gray disable color-palette border p-3 rounded">
                                    {{image.description|linebreaks}}
                                </div>


                                {% endif %}
                                <small class="form-text text-muted">
                                    <span class="badge badge-warning"> Info: </span>
                                    Describa brevemente el propósito de la imagen.
                                </small>
                            </div>
                        </div><!-- ./col Left-->

                        <div class="col">
                            {% if edit or delete %}
                            {% include 'core/selectbuild.html' %}
                            {% else %}
                            <div class="form-group">
                                <span class="text-warning">
                                    {{form.categories.label}}
                                </span>
                                {{form.categories}}
                            </div>
                            {% endif %}

                            <small class="form-text text-muted">
                                <span class="badge badge-warning"> Info: </span>
                                Selecciona un tipo de categoria.
                            </small>
                            <small class="form-text text-muted">
                                <span class="badge badge-danger"> Info: </span>
                                Como mínimo un tipo de categoría debe estar seleccionado.
                            </small>
                        </div><!-- ./col center-->

                        <div class="col">
                            <div class="form-group">

                                {% if edit or delete %}

                                <h5 class="text-warning">Imagen actual</h5>

                                {% comment %} Validating if is different of a pdf ext then show
                                the image else pdf
                                {% endcomment %}
                                {% if not image.file_ext == '.pdf' %}
                                <img class="" src="{{image.image.url}}" alt="{{image.image}}" width="200" height="200">
                                {% else %}
                                <img src="{% static 'core/custom/img/logo_pdf.png' %}" class="img-fluid mb-2" alt="{{img.title}}" />
                                {% endif %}
                                <br>
                                <small class="form-text text-muted">
                                    <span class="badge badge-primary">&nbsp; url:&nbsp; </span>
                                    {{image.image}}.
                                </small>
                                {% comment %} due to I am adding a image {% endcomment %}
                                {% else %}
                                <img src="{% static 'core/custom/img/upload-img.png' %}" alt="Upload Image" width="200" height="200">
                                {% endif %}


                                {% if edit or add %}
                                <br><br>
                                <div class="custom-file">
                                    {{form.image}}
                                    {% comment %} form.image return the id="id_image" {% endcomment %}
                                    <label class="custom-file-label" for="id_image">Selecciona un fichero</label>
                                </div>

                                <small class="form-text text-muted">
                                    <span class="badge badge-warning"> Info: </span>
                                    {{form.image.help_text}}.
                                </small>
                                {% endif %}

                            </div>
                        </div><!-- ./col right-->
                    </div>
                </div><!-- /.card-body -->
                {% comment %} Area of foother {% endcomment %}
                <div class="card-footer">
                    <a href="{% url 'core:dashboard' %}" type="button" class="btn btn-secondary  btn-sm">Cancelar</a>
                    {% if not delete %}
                    <button type="submit" id="submit_save" class="btn btn-primary btn-sm" disabled>
                        <i class="fas fa-plus-circle"></i> &nbsp; Guardar
                    </button>
                    {% else %}


                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger">
                        <i class="fas fa-trash-alt"></i> &nbsp; Eliminar
                    </button>
                    {% comment %} <button type="submit" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger">
                        <i class="fas fa-plus-circle"></i> &nbsp; Eliminar
                    </button> {% endcomment %}
                    {% endif %}

                </div><!-- /.card-footer -->
            </form>
        </div><!-- /.card -->


    </div>
</div>

{% include 'core/modaldanger.html' %}

{% endblock content %}


{% block script %}

{% comment %} Used to disable or enable the summit botton if a least one of category has been select {% endcomment %}
{% if not delete %}
<script src=" {% static '/core/custom/js/checkcategorieselected.js' %} "></script>
{% endif %}


<!-- SweetAlert2 -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/toastr/toastr.min.js' %}"></script>

{% comment %} show the name of the image appear on select {% endcomment %}
<script src=" {% static '/core/custom/js/shownamefile.js' %} "></script>


{% if delete %}
<script src=" {% static '/core/custom/js/checkdeleteconfirm.js' %} "></script>
{% endif %}


{% endblock script %}

core/templates/core/dashboard.html
{% extends "core/layout.html" %}
{% load static %}
{% load poll_extras %}
{% block title %} {% endblock %}

{% block styles %}
<!-- Ekko Lightbox -->
<link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/ekko-lightbox/ekko-lightbox.css' %}">

{% endblock styles %}

{% block content %}

<div class="row">
  <div class="col-12">
    <div class="card card-primary">
      <div class="card-header">
        <h4 class="card-title">Mis imágenes favoritas</h4>

      </div>
      <div class="card-body">
        <div class="input-group input-group-sm">
          <input class="form-control " type="text" placeholder="Buscar..." aria-label="Search" data-search>
          <div class="input-group-append">
            <button class="btn btn-navbar" type="text">
              <i class="fas fa-search text-warning"></i>
            </button>
          </div>
        </div>
        <hr>
        <div>


          <strong>Categorías diponibles:</strong>

          {% comment %} here I create the top of categories {% endcomment %}
          <div class="btn-group w-100 mb-2">
            <a class="btn btn-info active" data-filter="all"> Todas las imágenes </a>
            {% for category in categories %}
            <a class="btn btn-info" data-filter="{{category.pk}}"> {{category.description}} </a>
            {% endfor %}
          </div>


          <div class="mb-2">
            <a href=" {% url 'core:addimage'%}" class="open-modal-pet btn btn-secondary"><i class="fas fa-plus-circle"></i> &nbsp;Agregar una imagen</a>

            <a class="btn btn-secondary" data-shuffle><i class="fas fa-random"></i>&nbsp;Barajar imágenes </a>


            <div class="float-right">
              <select class="custom-select" style="width: auto;" data-sortOrder>
                <option value="index"> Ordenar posición </option>
                <option value="sortData"> Order por datos personalizados </option>
              </select>
              <div class="btn-group">
                <a class="btn btn-default" data-sortAsc> Ascendente </a>
                <a class="btn btn-default" data-sortDesc> Decendente </a>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class="filter-container p-0 row">
            {% for image in images %}

            {% comment %} Create each element into the filtr-item {% endcomment %}
            <div class="filtr-item col-sm-2 p-2 border border-dark" data-category="{{image.data_category}}" data-sort="{{image.title}}">

              {% comment %} show the title of file {% endcomment %}
              <div class="pb-2">
                <small class="form-text text-white">
                  <span class="badge badge-success"> Titulo: </span>
                  {{image.title}}
                </small>

              </div>

              {% comment %} Box to show images {% endcomment %}
              {% if not image.file_ext == '.pdf' %}
              <a href="{{image.image.url}}?text={{image.title}}" data-toggle="lightbox" data-title="{{image.title}}">
                <img src="{{image.image.url}}" class="img-fluid mb-2" alt="{{img.title}}" />
                {% else %}
                <img src="{% static 'core/custom/img/logo_pdf.png' %}" class="img-fluid mb-2" alt="{{img.title}}" />
                {% endif %}


                {% comment %} Area to show the filenale {% endcomment %}
                <small class="form-text text-white">
                  <span class="badge badge-warning"> Nombre: </span>
                  {{image|filename}}
                </small>

                {% comment %} Area to show the Description {% endcomment %}
                <small class="form-text text-white">
                  <span class="badge badge-info"> Descripción: </span>
                  {{image.description}}
                </small>

                <hr style="height:1px;border-width:0;color:white;background-color:Teal">
                {% comment %} Buttom to delete and modify {% endcomment %}
                <div class="float-right">
                  <a href=" {% url 'core:editimage'   image.pk %}" class="open-modal-pet btn btn-warning btn-xs"><i class="fas fa-pen"></i></a>
                  <a href=" {% url 'core:deleteimage' image.pk %}" class="open-modal-pet btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a>
                </div>
              </a><!-- /.image -->
            </div><!-- /.filtr-item -->

            {% endfor %}

          </div><!-- /.Filter-container -->
        </div>

      </div><!-- /.card-body -->
      {% comment %} Area of foother {% endcomment %}
      <div class="card-footer">
        <a href=" {% url 'core:addimage'%}" class="open-modal-pet btn btn-secondary"><i class="fas fa-plus-circle"></i> &nbsp;Agregar una imagen</a>
        <div class="float-right">
          <a class="open-modal-pet btn btn-secondary btn-xs"><i class="fas fa-plus-circle"></i></a> = Agregar |
          <a class="open-modal-pet btn btn-warning btn-xs"><i class="fas fa-pen"></i></a> = Modificar |
          <a class="open-modal-pet btn btn-danger btn-xs"><i class="fas fa-trash-alt"></i></a> = Eliminar
        </div>
      </div><!-- /.card-footer -->
    </div><!-- /.card -->
  </div><!-- /.col-12 -->
</div><!-- /.row -->

{% endblock content %}


{% block script %}

<!-- Page specific script -->
<!-- Filterizr-->
<script src="{% static 'lib/adminlte-3.2.0/plugins/filterizr/jquery.filterizr.min.js' %}"></script>

<script src=" {% static '/core/custom/js/galerymanagment.js' %} "></script>


{% endblock script %}

core/templates/core/footer.html
<footer class="main-footer">
  <strong>Copyright &copy; {% now 'Y' %}
    <a href=" {% url 'core:loginpage' %}">FotoDAM.io</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block"><b>Version</b> 1.0.0</div>
</footer>

core/templates/core/header.html
<div class="content-header">
  {% comment %} <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0"> <i class="fas fa-home"></i> {{work_area}}</h1>
      </div>
      <!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v2</li>
        </ol>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div> {% endcomment %}
  <!-- /.container-fluid -->
</div>

core/templates/core/iferror.html
{% if form.errors  %}
<div class="p-2 mb-0 mt-0 bg-gradient-danger text-white">
    {% for field in form %}
    {% for error in field.errors %}
    {{ error|escape }}
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    {{ error|escape }}
    {% endfor %}
</div>
{% endif %}

core/templates/core/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>{% block title %}{{apptitle}}{% endblock %}</title>


  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}" />


  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" />


  {% block styles %}
  {% endblock styles %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/dist/css/adminlte.min.css' %}">

  <!-- LOCAL CSS -->
  <link href="{% static 'core/custom/css/styles.css' %}" rel="stylesheet" />
</head>

<body class="hold-transition dark-mode layout-fixed layout-top-nav layout-footer-fixed ">
  <div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img class="animation__wobble" src="{% static 'core/custom/img/dam-logo.png' %}" alt="Foto DAM" height="60" width="60" />
    </div>

    <!-- Navbar -->
    {% include 'core/navbar.html' %}
    <!-- /.navbar -->

    {% comment %}
    <!-- Main Sidebar Container -->
    {% include 'core/sidebar.html' %} {% endcomment %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      {% include 'core/header.html' %}
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">

          {% include 'core/messages.html' %} {% comment %} This show any messages {% endcomment %}
          {% block content %} {% endblock content %}
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    {% include 'core/footer.html' %}
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>

  <!-- Bootstrap -->
  <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Ekko Lightbox -->
  <script src="{% static 'lib/adminlte-3.2.0/plugins/ekko-lightbox/ekko-lightbox.min.js' %}"></script>

  <!-- AdminLTE App -->
  <script src="{% static 'lib/adminlte-3.2.0/dist/js/adminlte.min.js' %}"></script>


  <!-- PAGE PLUGINS -->

  {% block script %} {% endblock script %}


</body>

</html>

core/templates/core/messages.html
<div class="row mt-3">
    <div class="col-12">
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif%}
        {% endfor %}
        {% endif %}
    </div>
</div>

core/templates/core/navbar.html
 {% load static %}


 <!-- Navbar -->
 <nav class="main-header navbar navbar-expand-md navbar-dark">
   <div class="container">
     <a href="{% url 'core:dashboard' %} " class="navbar-brand">
       <img src="{% static 'core/custom/img/dam-logo.png' %}" alt="Foto DAM" class="img-size-50 mr-3 img-circle">

       <strong> <span class="brand-text text-danger">FotoDAM</span></strong>
     </a>

     <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse order-3" id="navbarCollapse">
       <!-- Left navbar links -->
       <ul class="navbar-nav">

       </ul>

     </div>

     <!-- Right navbar links -->
     <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">

       <li class="nav-item">
         <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
           <i class="fas fa-user-astronaut"></i>&nbsp; <strong><span class="text-green"> {{request.user|upper}}</span> </strong>

         </a>
       </li>
       <li class="nav-item">
         <a class="nav-link" data-widget="" data-slide="true" href=" {% url 'core:logoutpage' %} " role="button">
           <i class="fas fa-sign-out-alt"></i>&nbsp; Salir
         </a>
       </li>
     </ul>
   </div>
 </nav>
 <!-- /.navbar -->

core/templates/core/selectbuild.html
<div class="form-group">
    <span class="text-warning">
        *Categorías actuales.
    </span>

    <div id="id_categories" class="category-check">
        {% if edit %}
        {% for selected in img_selected  %}
        <label for="id_categories_{{selected.pk}}">
            <input type="checkbox" name="categories" value="{{selected.pk}}" class="category-check" id="id_categories_{{selected.pk}}" checked>
            {{selected.description}}
        </label>
        <br>
        {% endfor %}
        <hr>


        <h5 class="text-primary">Categorías disponibles.</h5>
        {% for to_select in img_to_select  %}
        <label for="id_categories_{{to_select.pk}}">
            <input type="checkbox" name="categories" value="{{to_select.pk}}" class="category-check" id="id_categories_{{to_select.pk}}">
            {{to_select.description}}
        </label>
        <br>
        {% endfor %}

        {% elif delete %}
        {% for selected in img_selected  %}
        <label for="id_categories_{{selected.pk}}">
            <input type="checkbox" name="categories" value="{{selected.pk}}" class="category-check" id="id_categories_{{selected.pk}}" checked disabled>
            {{selected.description}}
        </label>
        <br>
        {% endfor %}
        {% endif %}



    </div>

</div>